### ISSUE TITLE
Reto resuelto!!!

### ISSUE THREAD

**Issue by andrsdev** [juandc/web-unicorn-challenge#1]
Espero haber cumplido con las exigencias del reto jajaja. Traté de buscar la tipografía más parecida pero no encontré una igual.

**Items solicitados:**

1. [Link](https://andrsdev.github.io/Unicorn-Challenge/index.html) para visualizar el resultado.
2. [Link](https://github.com/AndrsDev/Unicorn-Challenge) del código.
3. Imagen del resultado final:
![unicorn](https://user-images.githubusercontent.com/34043452/60225330-8ef28500-9843-11e9-9126-91d3bf8465c3.png)

**Extras:**

- Grid para layouts
- Animaciones
- Responsive

**Comment by juandc** [comment]
¡Andrés! ¡Felicitaciones! ¡Te quedó fantástico! Así como lo tienes está espectacular.

Recomendaciones:

- 📸Puedes poner tu foto en el cuadrito rojo. 
- 📱 ¡ES RESPONSIVE GENIAAAAAL! Podrías acomodar la imágen para que se pueda seguir viendo. Lo mismo con la barrita de la izquierda, solo desaparece y ya 😜 
- :art: Puedes primero hacer el diseño y luego los arreglos que quieras, así ganas más puntos :clap::smirk:

**Comment by juandc** [comment]
Ohh... Por cierto, disculpa por no especificar... La fuente era [Dosis](https://fonts.google.com/specimen/Dosis).
