### ISSUE TITLE
Reto Completado

### ISSUE THREAD

**Issue by gabrielelpidio** [juandc/web-unicorn-challenge#11]
### Código: https://github.com/gabrielelpidio/unicorn-challenge

**_Hecho con React y create-react-app._**

Extras:

- Responsive con CSS y un poco de ayuda de react-responsive
- Animaciones basadas en física de resortes con React Spring 
- CSS Grid en casi todo

_Pd: Not the cleanest CSS_

**Comment by juandc** [comment]
Hello Gabriel! ¡Excelente tu solución! ¡React también es un extra! 😆

Te menciono esto no más para que te quede lo mejor posible: el menu no queda completamente escondido en responsive:

![image](https://user-images.githubusercontent.com/15987317/61225770-dce20680-a6e6-11e9-91b1-d780998f331e.png)

De resto todo :ok_hand:...

**Comment by gabrielelpidio** [comment]
Resuelto! Gracias por el feedback!
